set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",alacritty:Tc" 
set -s escape-time 0
set -g mouse on
set -g allow-passthrough on
set -g set-clipboard on

unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix
# set-option -g prefix C-b
# bind-key C-b send-prefix

bind-key r source-file "$HOME/.config/tmux/tmux.conf" \; display "Reloaded tmux.conf"

set -g base-index 1

# set-window-option -g mode-keys vi
# bind -T copy-mode-vi v send-keys -X begin-selection
# bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

# panes
bind-key -r k select-pane -U
bind-key -r j select-pane -D
bind-key -r h select-pane -L
bind-key -r l select-pane -R

# tmux-sessionizer 
bind-key f run-shell "tmux new-window $HOME/.local/bin/tmux-sessionizer"
bind-key H switch-client -t "home"

source-file "$HOME/.config/tmux/tokyonight_moon.tmux"
